import type { HospitalState } from "./types";
import { HOSPITAL_NAME } from "./hospital";

export { HOSPITAL_NAME };
export const STATE_VERSION = 1;

export const seedState: HospitalState = {
  version: STATE_VERSION,
  role: "admin",
  patients: [
    {
      id: "pt-1001",
      mrn: "MRN-48219",
      firstName: "Elena",
      lastName: "Vasquez",
      age: 54,
      gender: "Female",
      bloodGroup: "O+",
      contact: "(415) 555-0142",
      email: "elena.vasquez@email.com",
      admittedAt: "2026-08-28T09:20:00.000Z",
      roomType: "Semi-Private",
      bed: "3B-12",
      dailyRoomRate: 890,
      attendingPhysician: "Dr. Priya Nair",
      status: "Admitted",
      diagnoses: ["Type 2 diabetes mellitus", "Community-acquired pneumonia"],
      allergies: [
        {
          id: "alg-1",
          substance: "Penicillin",
          reaction: "Anaphylaxis",
          severity: "Severe",
        },
        {
          id: "alg-2",
          substance: "Sulfa drugs",
          reaction: "Rash",
          severity: "Moderate",
        },
      ],
      vitals: [
        {
          id: "vit-1",
          recordedAt: "2026-09-09T06:10:00.000Z",
          systolic: 138,
          diastolic: 84,
          heartRate: 92,
          temperatureC: 37.8,
          spo2: 94,
          recordedBy: "RN Maya Chen",
        },
        {
          id: "vit-2",
          recordedAt: "2026-09-08T18:00:00.000Z",
          systolic: 132,
          diastolic: 80,
          heartRate: 88,
          temperatureC: 38.1,
          spo2: 93,
          recordedBy: "RN Maya Chen",
        },
      ],
      consultations: [
        {
          id: "con-1",
          date: "2026-09-08T14:30:00.000Z",
          clinician: "Dr. Priya Nair",
          department: "Pulmonology",
          diagnosis: "Community-acquired pneumonia",
          notes:
            "Chest X-ray shows right lower lobe infiltrate. Continue oxygen and non-penicillin antibiotic coverage. Monitor glucose closely.",
        },
        {
          id: "con-2",
          date: "2026-08-28T10:15:00.000Z",
          clinician: "Dr. James Okonkwo",
          department: "Internal Medicine",
          diagnosis: "Uncontrolled T2DM",
          notes:
            "Admission for dyspnea and hyperglycemia. Started basal-bolus insulin protocol.",
        },
      ],
    },
    {
      id: "pt-1002",
      mrn: "MRN-49102",
      firstName: "Marcus",
      lastName: "Hale",
      age: 67,
      gender: "Male",
      bloodGroup: "A-",
      contact: "(510) 555-0198",
      email: "marcus.hale@email.com",
      admittedAt: "2026-09-02T16:40:00.000Z",
      roomType: "ICU",
      bed: "ICU-04",
      dailyRoomRate: 2450,
      attendingPhysician: "Dr. Amira Hassan",
      status: "Admitted",
      diagnoses: ["NSTEMI", "Hypertension", "CKD stage 3"],
      allergies: [
        {
          id: "alg-3",
          substance: "Iodine contrast",
          reaction: "Hives and bronchospasm",
          severity: "Severe",
        },
      ],
      vitals: [
        {
          id: "vit-3",
          recordedAt: "2026-09-09T07:00:00.000Z",
          systolic: 118,
          diastolic: 72,
          heartRate: 64,
          temperatureC: 36.7,
          spo2: 98,
          recordedBy: "RN Luis Ortega",
        },
      ],
      consultations: [
        {
          id: "con-3",
          date: "2026-09-03T08:00:00.000Z",
          clinician: "Dr. Amira Hassan",
          department: "Cardiology",
          diagnosis: "NSTEMI",
          notes:
            "Troponin peaked at 4.2. Dual antiplatelet therapy. Cath deferred due to contrast allergy — discuss premedication vs alternative imaging.",
        },
      ],
    },
    {
      id: "pt-1003",
      mrn: "MRN-47011",
      firstName: "Aisha",
      lastName: "Rahman",
      age: 31,
      gender: "Female",
      bloodGroup: "B+",
      contact: "(628) 555-0110",
      email: "aisha.rahman@email.com",
      admittedAt: "2026-09-07T11:05:00.000Z",
      roomType: "Private",
      bed: "5A-02",
      dailyRoomRate: 1420,
      attendingPhysician: "Dr. Helen Cho",
      status: "Admitted",
      diagnoses: ["Postpartum recovery", "Iron-deficiency anemia"],
      allergies: [],
      vitals: [
        {
          id: "vit-4",
          recordedAt: "2026-09-09T05:45:00.000Z",
          systolic: 110,
          diastolic: 68,
          heartRate: 78,
          temperatureC: 36.9,
          spo2: 99,
          recordedBy: "RN Sofia Alvarez",
        },
      ],
      consultations: [
        {
          id: "con-4",
          date: "2026-09-07T12:00:00.000Z",
          clinician: "Dr. Helen Cho",
          department: "Obstetrics",
          diagnosis: "Uncomplicated vaginal delivery",
          notes: "Stable. Iron supplementation. Lactation support initiated.",
        },
      ],
    },
    {
      id: "pt-1004",
      mrn: "MRN-45590",
      firstName: "Robert",
      lastName: "Kim",
      age: 42,
      gender: "Male",
      bloodGroup: "AB+",
      contact: "(925) 555-0166",
      email: "robert.kim@email.com",
      admittedAt: "2026-09-05T08:00:00.000Z",
      roomType: "General Ward",
      bed: "2C-18",
      dailyRoomRate: 520,
      attendingPhysician: "Dr. James Okonkwo",
      status: "Admitted",
      diagnoses: ["Acute appendicitis — post-op day 4"],
      allergies: [
        {
          id: "alg-4",
          substance: "Latex",
          reaction: "Contact dermatitis",
          severity: "Mild",
        },
      ],
      vitals: [
        {
          id: "vit-5",
          recordedAt: "2026-09-09T06:30:00.000Z",
          systolic: 124,
          diastolic: 76,
          heartRate: 74,
          temperatureC: 37.1,
          spo2: 98,
          recordedBy: "RN Maya Chen",
        },
      ],
      consultations: [
        {
          id: "con-5",
          date: "2026-09-05T19:20:00.000Z",
          clinician: "Dr. James Okonkwo",
          department: "General Surgery",
          diagnosis: "Acute appendicitis",
          notes: "Laparoscopic appendectomy completed. Diet advancing. Wound clean.",
        },
      ],
    },
    {
      id: "pt-1005",
      mrn: "MRN-50144",
      firstName: "Nora",
      lastName: "Bennett",
      age: 78,
      gender: "Female",
      bloodGroup: "O-",
      contact: "(415) 555-0177",
      email: "nora.bennett@email.com",
      admittedAt: "2026-08-20T13:10:00.000Z",
      roomType: "Private",
      bed: "4A-08",
      dailyRoomRate: 1420,
      attendingPhysician: "Dr. Priya Nair",
      status: "Admitted",
      diagnoses: ["COPD exacerbation", "Atrial fibrillation"],
      allergies: [
        {
          id: "alg-5",
          substance: "Codeine",
          reaction: "Nausea and pruritus",
          severity: "Moderate",
        },
      ],
      vitals: [
        {
          id: "vit-6",
          recordedAt: "2026-09-09T06:00:00.000Z",
          systolic: 142,
          diastolic: 88,
          heartRate: 96,
          temperatureC: 36.8,
          spo2: 91,
          recordedBy: "RN Luis Ortega",
        },
      ],
      consultations: [
        {
          id: "con-6",
          date: "2026-09-01T09:40:00.000Z",
          clinician: "Dr. Priya Nair",
          department: "Pulmonology",
          diagnosis: "COPD exacerbation",
          notes:
            "Nebulizers q4h. Prednisone taper. Target SpO2 88–92%. Rate-controlled AFib.",
        },
      ],
    },
    {
      id: "pt-1006",
      mrn: "MRN-51208",
      firstName: "Daniel",
      lastName: "Okafor",
      age: 9,
      gender: "Male",
      bloodGroup: "A+",
      contact: "(650) 555-0133",
      email: "parent.okafor@email.com",
      admittedAt: "2026-09-08T20:15:00.000Z",
      roomType: "Semi-Private",
      bed: "PED-06",
      dailyRoomRate: 760,
      attendingPhysician: "Dr. Helen Cho",
      status: "Admitted",
      diagnoses: ["Asthma exacerbation"],
      allergies: [
        {
          id: "alg-6",
          substance: "Aspirin",
          reaction: "Wheezing",
          severity: "Severe",
        },
      ],
      vitals: [
        {
          id: "vit-7",
          recordedAt: "2026-09-09T07:15:00.000Z",
          systolic: 102,
          diastolic: 64,
          heartRate: 110,
          temperatureC: 37.4,
          spo2: 96,
          recordedBy: "RN Sofia Alvarez",
        },
      ],
      consultations: [
        {
          id: "con-7",
          date: "2026-09-08T21:00:00.000Z",
          clinician: "Dr. Helen Cho",
          department: "Pediatrics",
          diagnosis: "Moderate asthma exacerbation",
          notes: "Albuterol/ipratropium. Oral steroids. Aspirin allergy flagged.",
        },
      ],
    },
    {
      id: "pt-1007",
      mrn: "MRN-39880",
      firstName: "Grace",
      lastName: "Patel",
      age: 61,
      gender: "Female",
      bloodGroup: "B-",
      contact: "(408) 555-0184",
      email: "grace.patel@email.com",
      admittedAt: "2026-09-01T07:50:00.000Z",
      roomType: "General Ward",
      bed: "1D-22",
      dailyRoomRate: 520,
      attendingPhysician: "Dr. James Okonkwo",
      status: "Admitted",
      diagnoses: ["Cellulitis of left lower extremity"],
      allergies: [],
      vitals: [
        {
          id: "vit-8",
          recordedAt: "2026-09-09T06:20:00.000Z",
          systolic: 128,
          diastolic: 78,
          heartRate: 82,
          temperatureC: 37.6,
          spo2: 97,
          recordedBy: "RN Maya Chen",
        },
      ],
      consultations: [
        {
          id: "con-8",
          date: "2026-09-01T09:00:00.000Z",
          clinician: "Dr. James Okonkwo",
          department: "Internal Medicine",
          diagnosis: "Lower extremity cellulitis",
          notes: "IV antibiotics. Wound care BID. Mark erythema border daily.",
        },
      ],
    },
    {
      id: "pt-1008",
      mrn: "MRN-42033",
      firstName: "Thomas",
      lastName: "Nguyen",
      age: 49,
      gender: "Male",
      bloodGroup: "O+",
      contact: "(415) 555-0129",
      email: "thomas.nguyen@email.com",
      admittedAt: "2026-09-06T15:25:00.000Z",
      roomType: "Semi-Private",
      bed: "3A-09",
      dailyRoomRate: 890,
      attendingPhysician: "Dr. Amira Hassan",
      status: "Admitted",
      diagnoses: ["Nephrolithiasis", "Hydronephrosis"],
      allergies: [
        {
          id: "alg-7",
          substance: "Morphine",
          reaction: "Respiratory depression history",
          severity: "Severe",
        },
      ],
      vitals: [
        {
          id: "vit-9",
          recordedAt: "2026-09-09T05:50:00.000Z",
          systolic: 136,
          diastolic: 86,
          heartRate: 90,
          temperatureC: 37.0,
          spo2: 98,
          recordedBy: "RN Luis Ortega",
        },
      ],
      consultations: [
        {
          id: "con-9",
          date: "2026-09-06T16:10:00.000Z",
          clinician: "Dr. Amira Hassan",
          department: "Urology",
          diagnosis: "Obstructing 7mm ureteral stone",
          notes:
            "IV fluids, NSAIDs for pain. Avoid opioids given morphine sensitivity. Urology follow-up for possible stent.",
        },
      ],
    },
  ],
  medicines: [
    {
      id: "med-01",
      name: "Amoxicillin-Clavulanate",
      genericName: "amoxicillin / clavulanate",
      strength: "875/125 mg",
      form: "Tablet",
      manufacturer: "Northwind Pharma",
      batchNumber: "AC-88421",
      expiryDate: "2027-04-30",
      stock: 240,
      unitPrice: 2.4,
      location: "Aisle B / Bin 12",
    },
    {
      id: "med-02",
      name: "Azithromycin",
      genericName: "azithromycin",
      strength: "500 mg",
      form: "Tablet",
      manufacturer: "Helix Labs",
      batchNumber: "AZ-11029",
      expiryDate: "2026-10-12",
      stock: 38,
      unitPrice: 3.1,
      location: "Aisle B / Bin 08",
    },
    {
      id: "med-03",
      name: "Metformin",
      genericName: "metformin HCl",
      strength: "1000 mg",
      form: "Tablet",
      manufacturer: "Summit Generics",
      batchNumber: "MF-55201",
      expiryDate: "2028-01-15",
      stock: 420,
      unitPrice: 0.35,
      location: "Aisle C / Bin 03",
    },
    {
      id: "med-04",
      name: "Insulin Glargine",
      genericName: "insulin glargine",
      strength: "100 units/mL",
      form: "Vial",
      manufacturer: "Apex Biologics",
      batchNumber: "IG-77310",
      expiryDate: "2026-11-01",
      stock: 22,
      unitPrice: 48.0,
      location: "Cold chain / Fridge 2",
    },
    {
      id: "med-05",
      name: "Aspirin",
      genericName: "acetylsalicylic acid",
      strength: "81 mg",
      form: "Tablet",
      manufacturer: "Summit Generics",
      batchNumber: "AS-90012",
      expiryDate: "2027-08-20",
      stock: 600,
      unitPrice: 0.12,
      location: "Aisle A / Bin 01",
    },
    {
      id: "med-06",
      name: "Clopidogrel",
      genericName: "clopidogrel",
      strength: "75 mg",
      form: "Tablet",
      manufacturer: "Helix Labs",
      batchNumber: "CL-44190",
      expiryDate: "2027-02-28",
      stock: 145,
      unitPrice: 1.85,
      location: "Aisle A / Bin 14",
    },
    {
      id: "med-07",
      name: "Albuterol",
      genericName: "albuterol sulfate",
      strength: "2.5 mg/3 mL",
      form: "Nebule",
      manufacturer: "Coastal Respiratory",
      batchNumber: "AL-22881",
      expiryDate: "2026-09-28",
      stock: 64,
      unitPrice: 1.2,
      location: "Aisle D / Bin 05",
    },
    {
      id: "med-08",
      name: "Prednisone",
      genericName: "prednisone",
      strength: "20 mg",
      form: "Tablet",
      manufacturer: "Summit Generics",
      batchNumber: "PR-33044",
      expiryDate: "2028-06-01",
      stock: 180,
      unitPrice: 0.4,
      location: "Aisle C / Bin 19",
    },
    {
      id: "med-09",
      name: "Ceftriaxone",
      genericName: "ceftriaxone",
      strength: "1 g",
      form: "Vial",
      manufacturer: "Northwind Pharma",
      batchNumber: "CF-66712",
      expiryDate: "2027-12-10",
      stock: 41,
      unitPrice: 12.5,
      location: "IV room / Shelf 3",
    },
    {
      id: "med-10",
      name: "Ketorolac",
      genericName: "ketorolac tromethamine",
      strength: "30 mg/mL",
      form: "Injection",
      manufacturer: "Helix Labs",
      batchNumber: "KT-11903",
      expiryDate: "2026-10-05",
      stock: 90,
      unitPrice: 4.75,
      location: "IV room / Shelf 1",
    },
    {
      id: "med-11",
      name: "Ferrous Sulfate",
      genericName: "ferrous sulfate",
      strength: "325 mg",
      form: "Tablet",
      manufacturer: "Summit Generics",
      batchNumber: "FE-20880",
      expiryDate: "2028-03-22",
      stock: 310,
      unitPrice: 0.18,
      location: "Aisle C / Bin 07",
    },
    {
      id: "med-12",
      name: "Furosemide",
      genericName: "furosemide",
      strength: "40 mg",
      form: "Tablet",
      manufacturer: "Northwind Pharma",
      batchNumber: "FU-77440",
      expiryDate: "2027-09-14",
      stock: 28,
      unitPrice: 0.55,
      location: "Aisle A / Bin 22",
    },
  ],
  prescriptions: [
    {
      id: "rx-8001",
      patientId: "pt-1001",
      prescribedBy: "Dr. Priya Nair",
      prescribedAt: "2026-09-08T15:00:00.000Z",
      status: "Active",
      notes: "Avoid penicillin class. Azithromycin for CAP coverage.",
      items: [
        {
          medicineId: "med-02",
          medicineName: "Azithromycin 500 mg",
          dosage: "500 mg",
          frequency: "Daily x 3 days",
          quantity: 3,
          unitPrice: 3.1,
        },
        {
          medicineId: "med-04",
          medicineName: "Insulin Glargine",
          dosage: "18 units",
          frequency: "Nightly",
          quantity: 1,
          unitPrice: 48.0,
        },
      ],
    },
    {
      id: "rx-8002",
      patientId: "pt-1002",
      prescribedBy: "Dr. Amira Hassan",
      prescribedAt: "2026-09-03T09:10:00.000Z",
      status: "Dispensed",
      dispensedAt: "2026-09-03T10:02:00.000Z",
      dispensedBy: "Pharm. David Park",
      notes: "DAPT. Confirm no aspirin allergy — none on file.",
      items: [
        {
          medicineId: "med-05",
          medicineName: "Aspirin 81 mg",
          dosage: "81 mg",
          frequency: "Daily",
          quantity: 7,
          unitPrice: 0.12,
        },
        {
          medicineId: "med-06",
          medicineName: "Clopidogrel 75 mg",
          dosage: "75 mg",
          frequency: "Daily",
          quantity: 7,
          unitPrice: 1.85,
        },
      ],
    },
    {
      id: "rx-8003",
      patientId: "pt-1006",
      prescribedBy: "Dr. Helen Cho",
      prescribedAt: "2026-09-08T21:20:00.000Z",
      status: "Active",
      notes: "Aspirin allergy — do not dispense ASA. Nebulizer + steroid.",
      items: [
        {
          medicineId: "med-07",
          medicineName: "Albuterol nebule",
          dosage: "2.5 mg",
          frequency: "q4h PRN",
          quantity: 12,
          unitPrice: 1.2,
        },
        {
          medicineId: "med-08",
          medicineName: "Prednisone 20 mg",
          dosage: "20 mg",
          frequency: "Daily x 5 days",
          quantity: 5,
          unitPrice: 0.4,
        },
      ],
    },
    {
      id: "rx-8004",
      patientId: "pt-1007",
      prescribedBy: "Dr. James Okonkwo",
      prescribedAt: "2026-09-01T09:30:00.000Z",
      status: "Dispensed",
      dispensedAt: "2026-09-01T10:15:00.000Z",
      dispensedBy: "Pharm. Lila Brooks",
      notes: "IV ceftriaxone until afebrile 48h.",
      items: [
        {
          medicineId: "med-09",
          medicineName: "Ceftriaxone 1 g",
          dosage: "1 g",
          frequency: "IV q24h",
          quantity: 5,
          unitPrice: 12.5,
        },
      ],
    },
    {
      id: "rx-8005",
      patientId: "pt-1008",
      prescribedBy: "Dr. Amira Hassan",
      prescribedAt: "2026-09-06T16:40:00.000Z",
      status: "Active",
      notes: "Morphine allergy — NSAID analgesia only.",
      items: [
        {
          medicineId: "med-10",
          medicineName: "Ketorolac 30 mg",
          dosage: "15 mg",
          frequency: "IV q6h PRN pain",
          quantity: 4,
          unitPrice: 4.75,
        },
      ],
    },
    {
      id: "rx-8006",
      patientId: "pt-1003",
      prescribedBy: "Dr. Helen Cho",
      prescribedAt: "2026-09-07T13:00:00.000Z",
      status: "Active",
      notes: "Oral iron. Take with food if GI upset.",
      items: [
        {
          medicineId: "med-11",
          medicineName: "Ferrous Sulfate 325 mg",
          dosage: "325 mg",
          frequency: "Daily",
          quantity: 14,
          unitPrice: 0.18,
        },
      ],
    },
  ],
  invoices: [
    {
      id: "inv-1001",
      patientId: "pt-1001",
      discountPercent: 0,
      taxPercent: 8.25,
      insuranceProvider: "Blue Harbor PPO",
      insuranceCoveragePercent: 80,
      deductible: 500,
      copay: 40,
      amountPaid: 0,
      paymentStatus: "Pending",
      lineItems: [
        {
          id: "li-1001-c",
          category: "Consultation",
          description: "Pulmonology consult — Dr. Nair",
          quantity: 1,
          unitPrice: 385,
          createdAt: "2026-09-08T14:35:00.000Z",
        },
        {
          id: "li-1001-l",
          category: "Lab",
          description: "CBC, BMP, blood cultures, chest X-ray",
          quantity: 1,
          unitPrice: 640,
          createdAt: "2026-08-28T11:00:00.000Z",
        },
      ],
    },
    {
      id: "inv-1002",
      patientId: "pt-1002",
      discountPercent: 5,
      taxPercent: 8.25,
      insuranceProvider: "Summit Medicare Advantage",
      insuranceCoveragePercent: 90,
      deductible: 250,
      copay: 25,
      amountPaid: 400,
      paymentStatus: "Partially Paid",
      lineItems: [
        {
          id: "li-1002-c",
          category: "Consultation",
          description: "Cardiology consult — Dr. Hassan",
          quantity: 1,
          unitPrice: 520,
          createdAt: "2026-09-03T08:05:00.000Z",
        },
        {
          id: "li-1002-l",
          category: "Lab",
          description: "Serial troponin, ECG, echocardiogram",
          quantity: 1,
          unitPrice: 1280,
          createdAt: "2026-09-02T18:00:00.000Z",
        },
        {
          id: "li-1002-p",
          category: "Pharmacy",
          description: "Rx rx-8002 — Aspirin + Clopidogrel",
          quantity: 1,
          unitPrice: 13.79,
          createdAt: "2026-09-03T10:02:00.000Z",
          linkedPrescriptionId: "rx-8002",
        },
      ],
    },
    {
      id: "inv-1003",
      patientId: "pt-1003",
      discountPercent: 0,
      taxPercent: 8.25,
      insuranceProvider: "Harbor Family Plan",
      insuranceCoveragePercent: 70,
      deductible: 200,
      copay: 30,
      amountPaid: 0,
      paymentStatus: "Pending",
      lineItems: [
        {
          id: "li-1003-c",
          category: "Consultation",
          description: "OB postpartum visit — Dr. Cho",
          quantity: 1,
          unitPrice: 310,
          createdAt: "2026-09-07T12:05:00.000Z",
        },
        {
          id: "li-1003-l",
          category: "Lab",
          description: "CBC and iron studies",
          quantity: 1,
          unitPrice: 210,
          createdAt: "2026-09-07T13:20:00.000Z",
        },
      ],
    },
    {
      id: "inv-1004",
      patientId: "pt-1004",
      discountPercent: 0,
      taxPercent: 8.25,
      insuranceProvider: "Self-pay",
      insuranceCoveragePercent: 0,
      deductible: 0,
      copay: 0,
      amountPaid: 0,
      paymentStatus: "Pending",
      lineItems: [
        {
          id: "li-1004-p",
          category: "Procedure",
          description: "Laparoscopic appendectomy",
          quantity: 1,
          unitPrice: 8600,
          createdAt: "2026-09-05T19:30:00.000Z",
        },
        {
          id: "li-1004-c",
          category: "Consultation",
          description: "Surgical follow-up",
          quantity: 2,
          unitPrice: 185,
          createdAt: "2026-09-06T09:00:00.000Z",
        },
      ],
    },
    {
      id: "inv-1005",
      patientId: "pt-1005",
      discountPercent: 10,
      taxPercent: 8.25,
      insuranceProvider: "Blue Harbor PPO",
      insuranceCoveragePercent: 80,
      deductible: 500,
      copay: 40,
      amountPaid: 2450.12,
      paymentStatus: "Settled",
      lineItems: [
        {
          id: "li-1005-c",
          category: "Consultation",
          description: "Pulmonology + cardiology bundle",
          quantity: 1,
          unitPrice: 640,
          createdAt: "2026-09-01T09:45:00.000Z",
        },
        {
          id: "li-1005-l",
          category: "Lab",
          description: "ABG, BNP, chest CT",
          quantity: 1,
          unitPrice: 980,
          createdAt: "2026-08-20T15:00:00.000Z",
        },
      ],
    },
    {
      id: "inv-1006",
      patientId: "pt-1006",
      discountPercent: 0,
      taxPercent: 8.25,
      insuranceProvider: "Harbor Family Plan",
      insuranceCoveragePercent: 85,
      deductible: 100,
      copay: 20,
      amountPaid: 0,
      paymentStatus: "Pending",
      lineItems: [
        {
          id: "li-1006-c",
          category: "Consultation",
          description: "Pediatric emergency + admit",
          quantity: 1,
          unitPrice: 450,
          createdAt: "2026-09-08T21:05:00.000Z",
        },
      ],
    },
    {
      id: "inv-1007",
      patientId: "pt-1007",
      discountPercent: 0,
      taxPercent: 8.25,
      insuranceProvider: "Summit Choice HMO",
      insuranceCoveragePercent: 75,
      deductible: 350,
      copay: 35,
      amountPaid: 150,
      paymentStatus: "Partially Paid",
      lineItems: [
        {
          id: "li-1007-c",
          category: "Consultation",
          description: "Internal medicine admit",
          quantity: 1,
          unitPrice: 275,
          createdAt: "2026-09-01T09:05:00.000Z",
        },
        {
          id: "li-1007-p",
          category: "Pharmacy",
          description: "Rx rx-8004 — Ceftriaxone 1 g x5",
          quantity: 1,
          unitPrice: 62.5,
          createdAt: "2026-09-01T10:15:00.000Z",
          linkedPrescriptionId: "rx-8004",
        },
      ],
    },
    {
      id: "inv-1008",
      patientId: "pt-1008",
      discountPercent: 0,
      taxPercent: 8.25,
      insuranceProvider: "Blue Harbor PPO",
      insuranceCoveragePercent: 80,
      deductible: 500,
      copay: 40,
      amountPaid: 0,
      paymentStatus: "Pending",
      lineItems: [
        {
          id: "li-1008-c",
          category: "Consultation",
          description: "Urology consult — Dr. Hassan",
          quantity: 1,
          unitPrice: 410,
          createdAt: "2026-09-06T16:15:00.000Z",
        },
        {
          id: "li-1008-l",
          category: "Lab",
          description: "CT KUB, urinalysis, BMP",
          quantity: 1,
          unitPrice: 890,
          createdAt: "2026-09-06T16:45:00.000Z",
        },
      ],
    },
  ],
  staff: [
    {
      id: "st-01",
      employeeId: "EMP-2041",
      name: "Dr. Vignesh Arumugam",
      department: "Doctors",
      title: "Consultant Orthopaedic Surgeon",
      email: "p.nair@meridian.hospital",
      hiredAt: "2018-03-12",
      baseSalary: 18500,
      overtimeRate: 145,
      nightShiftBonus: 280,
      healthPremium: 420,
      unpaidLeavePenaltyPerDay: 620,
    },
    {
      id: "st-02",
      employeeId: "EMP-1988",
      name: "Dr. Amira Hassan",
      department: "Doctors",
      title: "Cardiologist",
      email: "a.hassan@meridian.hospital",
      hiredAt: "2016-07-01",
      baseSalary: 21200,
      overtimeRate: 160,
      nightShiftBonus: 300,
      healthPremium: 420,
      unpaidLeavePenaltyPerDay: 710,
    },
    {
      id: "st-03",
      employeeId: "EMP-2210",
      name: "Dr. James Okonkwo",
      department: "Doctors",
      title: "General Surgeon",
      email: "j.okonkwo@meridian.hospital",
      hiredAt: "2019-11-04",
      baseSalary: 19800,
      overtimeRate: 150,
      nightShiftBonus: 290,
      healthPremium: 420,
      unpaidLeavePenaltyPerDay: 660,
    },
    {
      id: "st-04",
      employeeId: "EMP-2304",
      name: "Dr. Helen Cho",
      department: "Doctors",
      title: "OB / Pediatric Hospitalist",
      email: "h.cho@meridian.hospital",
      hiredAt: "2021-02-15",
      baseSalary: 16400,
      overtimeRate: 130,
      nightShiftBonus: 260,
      healthPremium: 390,
      unpaidLeavePenaltyPerDay: 545,
    },
    {
      id: "st-05",
      employeeId: "EMP-3102",
      name: "Maya Chen, RN",
      department: "Nurses",
      title: "Charge Nurse — Med/Surg",
      email: "m.chen@meridian.hospital",
      hiredAt: "2017-05-22",
      baseSalary: 7800,
      overtimeRate: 62,
      nightShiftBonus: 140,
      healthPremium: 265,
      unpaidLeavePenaltyPerDay: 260,
    },
    {
      id: "st-06",
      employeeId: "EMP-3340",
      name: "Luis Ortega, RN",
      department: "Nurses",
      title: "ICU Nurse",
      email: "l.ortega@meridian.hospital",
      hiredAt: "2020-09-08",
      baseSalary: 8200,
      overtimeRate: 68,
      nightShiftBonus: 175,
      healthPremium: 265,
      unpaidLeavePenaltyPerDay: 275,
    },
    {
      id: "st-07",
      employeeId: "EMP-3488",
      name: "Sofia Alvarez, RN",
      department: "Nurses",
      title: "Pediatric / L&D Nurse",
      email: "s.alvarez@meridian.hospital",
      hiredAt: "2022-01-10",
      baseSalary: 7200,
      overtimeRate: 58,
      nightShiftBonus: 130,
      healthPremium: 250,
      unpaidLeavePenaltyPerDay: 240,
    },
    {
      id: "st-08",
      employeeId: "EMP-4101",
      name: "David Park, PharmD",
      department: "Pharmacists",
      title: "Clinical Pharmacist",
      email: "d.park@meridian.hospital",
      hiredAt: "2018-08-19",
      baseSalary: 9800,
      overtimeRate: 74,
      nightShiftBonus: 120,
      healthPremium: 280,
      unpaidLeavePenaltyPerDay: 325,
    },
    {
      id: "st-09",
      employeeId: "EMP-4220",
      name: "Lila Brooks, PharmD",
      department: "Pharmacists",
      title: "Inpatient Dispensing Lead",
      email: "l.brooks@meridian.hospital",
      hiredAt: "2023-04-03",
      baseSalary: 9100,
      overtimeRate: 70,
      nightShiftBonus: 110,
      healthPremium: 280,
      unpaidLeavePenaltyPerDay: 300,
    },
    {
      id: "st-10",
      employeeId: "EMP-1014",
      name: "Anita Desai",
      department: "Admins",
      title: "Hospital Administrator",
      email: "a.desai@meridian.hospital",
      hiredAt: "2014-01-06",
      baseSalary: 12500,
      overtimeRate: 0,
      nightShiftBonus: 0,
      healthPremium: 310,
      unpaidLeavePenaltyPerDay: 415,
    },
    {
      id: "st-11",
      employeeId: "EMP-1188",
      name: "Chris Lang",
      department: "Admins",
      title: "Revenue Cycle Manager",
      email: "c.lang@meridian.hospital",
      hiredAt: "2019-06-17",
      baseSalary: 8900,
      overtimeRate: 45,
      nightShiftBonus: 0,
      healthPremium: 290,
      unpaidLeavePenaltyPerDay: 295,
    },
    {
      id: "st-12",
      employeeId: "EMP-1266",
      name: "Jordan Miles",
      department: "Admins",
      title: "Payroll Specialist",
      email: "j.miles@meridian.hospital",
      hiredAt: "2024-03-11",
      baseSalary: 6400,
      overtimeRate: 38,
      nightShiftBonus: 0,
      healthPremium: 240,
      unpaidLeavePenaltyPerDay: 210,
    },
  ],
  payslips: [
    {
      id: "pay-01",
      staffId: "st-01",
      period: "2026-08",
      overtimeHours: 6,
      nightShifts: 2,
      unpaidLeaveDays: 0,
      taxPercent: 28,
      paidOn: "2026-08-31",
    },
    {
      id: "pay-02",
      staffId: "st-01",
      period: "2026-07",
      overtimeHours: 2,
      nightShifts: 1,
      unpaidLeaveDays: 0,
      taxPercent: 28,
      paidOn: "2026-07-31",
    },
    {
      id: "pay-03",
      staffId: "st-01",
      period: "2026-06",
      overtimeHours: 0,
      nightShifts: 0,
      unpaidLeaveDays: 1,
      taxPercent: 28,
      paidOn: "2026-06-30",
    },
    {
      id: "pay-04",
      staffId: "st-05",
      period: "2026-08",
      overtimeHours: 14,
      nightShifts: 6,
      unpaidLeaveDays: 0,
      taxPercent: 22,
      paidOn: "2026-08-31",
    },
    {
      id: "pay-05",
      staffId: "st-05",
      period: "2026-07",
      overtimeHours: 8,
      nightShifts: 5,
      unpaidLeaveDays: 1,
      taxPercent: 22,
      paidOn: "2026-07-31",
    },
    {
      id: "pay-06",
      staffId: "st-08",
      period: "2026-08",
      overtimeHours: 4,
      nightShifts: 2,
      unpaidLeaveDays: 0,
      taxPercent: 24,
      paidOn: "2026-08-31",
    },
    {
      id: "pay-07",
      staffId: "st-10",
      period: "2026-08",
      overtimeHours: 0,
      nightShifts: 0,
      unpaidLeaveDays: 0,
      taxPercent: 26,
      paidOn: "2026-08-31",
    },
    {
      id: "pay-08",
      staffId: "st-06",
      period: "2026-08",
      overtimeHours: 18,
      nightShifts: 8,
      unpaidLeaveDays: 0,
      taxPercent: 22,
      paidOn: "2026-08-31",
    },
    {
      id: "pay-09",
      staffId: "st-02",
      period: "2026-08",
      overtimeHours: 3,
      nightShifts: 1,
      unpaidLeaveDays: 0,
      taxPercent: 30,
      paidOn: "2026-08-31",
    },
    {
      id: "pay-10",
      staffId: "st-09",
      period: "2026-08",
      overtimeHours: 5,
      nightShifts: 3,
      unpaidLeaveDays: 0,
      taxPercent: 24,
      paidOn: "2026-08-31",
    },
    {
      id: "pay-11",
      staffId: "st-04",
      period: "2026-08",
      overtimeHours: 10,
      nightShifts: 3,
      unpaidLeaveDays: 0,
      taxPercent: 26,
      paidOn: "2026-08-31",
    },
    {
      id: "pay-12",
      staffId: "st-12",
      period: "2026-08",
      overtimeHours: 6,
      nightShifts: 0,
      unpaidLeaveDays: 0,
      taxPercent: 20,
      paidOn: "2026-07-31",
    },
  ],
};
